import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
            >
                <nav className="bg-slate-900 text-white p-4 shadow-lg">
                    <div className="container mx-auto flex justify-between items-center">
                        <div className="flex items-center gap-3">
                            <i className="fa-solid fa-database text-emerald-400 text-xl"></i>
                            <h1 className="text-xl font-bold tracking-tight">CSQL <span
                                className="text-slate-400 font-normal text-sm">Demo</span></h1>
                        </div>
                        <div className="flex items-center gap-4">
                            <div id="db-status"
                                className="flex items-center gap-2 text-xs bg-slate-800 px-3 py-1 rounded-full border border-slate-700">
                                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                                Connected to Engine
                            </div>
                        </div>
                    </div>
                </nav>

                {children}
            </body>
        </html>
    );
}
